import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TopBar from './components/TopBar/TopBar'
// import { getServerSession } from 'next-auth'

import './globals.css'
import Providers from './Providers/Providers'
import Footer from './components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Meetings',
  description: 'Generated by YeonV'
}

export const dynamic = 'force-dynamic'

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  // const session = await getServerSession()

  return (
    <html lang='en'>
      <link rel='icon' href='/favicon.ico' sizes='any' />
      <body className={inter.className}>
        <Providers>
          <TopBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
