import type { Metadata, Viewport } from 'next'
import type { ReactNode } from 'react'

import { Inter } from 'next/font/google'
import TopBar from './components/TopBar/TopBar'
// import { getServerSession } from 'next-auth'

import './globals.css'
import Providers from './Providers/Providers'
import Footer from './components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

const APP_NAME = 'YZ AppStack'
const APP_DEFAULT_TITLE = 'AppStack'
const APP_TITLE_TEMPLATE = '%s - YZ'
const APP_DESCRIPTION = 'Generated by YeonV'

export const metadata: Metadata = {
  applicationName: APP_NAME,
  title: {
    default: APP_DEFAULT_TITLE,
    template: APP_TITLE_TEMPLATE
  },
  description: APP_DESCRIPTION,
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: APP_DEFAULT_TITLE
    // startUpImage: [],
  },
  formatDetection: {
    telephone: false
  },
  openGraph: {
    type: 'website',
    siteName: APP_NAME,
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE
    },
    description: APP_DESCRIPTION
  },
  twitter: {
    card: 'summary',
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE
    },
    description: APP_DESCRIPTION
  }
}

export const viewport: Viewport = {
  themeColor: '#FFFFFF'
}

export const dynamic = 'force-dynamic'

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  // const session = await getServerSession()

  return (
    <html lang='en'>
      <link rel='icon' href='/favicon.ico' sizes='any' />
      <body className={inter.className}>
        <Providers>
          <TopBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
