import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import { ThemeProvider } from './Providers/ThemeProvider'
import { NextAuthProvider } from './Providers/SessionProvider'
import TopBar from './components/TopBar/TopBar'
import './globals.css'
import { WebSocketProvider } from 'next-ws/client'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Meetings',
  description: 'Generated by YeonV'
}

export const dynamic = 'force-dynamic'

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()

  return (
    <html lang='en'>
      <link rel='icon' href='/favicon.ico' sizes='any' />
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider>
            <NextAuthProvider>
              <TopBar />
              {children}

              {/* {session && session.user ? (
                <div>
                  <p>Authenticated</p>
                </div>
              ) : (
                <div>
                  <p>Not authenticated</p>
                </div>
              )} */}
            </NextAuthProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
