version: '3'
services:

  yznextprod:
    image: yznextprod
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PORT: ${NEXT_PORT}
    container_name: yznextprod
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${SUB_DOMAIN}.${BASE_DOMAIN}
      VIRTUAL_PORT: ${NEXT_PORT}
      LETSENCRYPT_HOST: ${SUB_DOMAIN}.${BASE_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    ports:
      - "${NEXT_PORT}:${NEXT_PORT}"
    depends_on:
      - yzstrapiDB

  yznextdev:
    image: yznextdev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        NEXT_DEV_PORT: ${NEXT_DEV_PORT}
        NEXT_PUBLIC_STAGE: dev
    container_name: yznextdev
    restart: always
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/package.json:/usr/src/app/package.json
      - ./frontend/package-lock.json:/usr/src/app/package-lock.json
      - ./frontend/tsconfig.json:/usr/src/app/tsconfig.json
      - ./frontend/.eslintrc.json:/usr/src/app/.eslintrc.json
    env_file: .env
    environment:
      VIRTUAL_HOST: ${SUB_DOMAIN}-dev.${BASE_DOMAIN}
      VIRTUAL_PORT: ${NEXT_DEV_PORT}
      LETSENCRYPT_HOST: ${SUB_DOMAIN}-dev.${BASE_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      NEXT_PUBLIC_STAGE: dev
    ports:
      - "${NEXT_DEV_PORT}:${NEXT_DEV_PORT}"
    depends_on:
      - yzstrapiDB

 
  yzstrapiweb:
    container_name: yzstrapiweb
    image: blade86/strapi-v4:latest-amd64
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: yzstrapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      VIRTUAL_HOST: ${STRAPI_SUB_DOMAIN}.${BASE_DOMAIN}
      VIRTUAL_PORT: ${STRAPI_PORT}
      LETSENCRYPT_HOST: ${STRAPI_SUB_DOMAIN}.${BASE_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - ./.env:/opt/app/.env
      - ./backend/public:/opt/app/public
      - ./backend/config/sync:/opt/app/config/sync
      - ./backend/migrations:/opt/app/migrations
      - ./backend/api:/opt/app/src/api
      - ./backend/types:/opt/app/types
      - ./backend/src/extensions/users-permissions/content-types/user:/opt/app/src/extensions/users-permissions/content-types/user
      #MAC - ${PWD}/backend/config/plugins.ts:/opt/app/config/plugins.ts
      #MAC - ${PWD}/backend/tsconfig.json:/opt/app/tsconfig.json
      #WIN - ./backend/config/plugins.ts:/opt/app/config/plugins.ts
      #WIN - ./backend/tsconfig.json:/opt/app/tsconfig.json
    ports:
      - '${STRAPI_PORT}:1337'
    depends_on:
      - yzstrapiDB

  yzstrapiDB:
    container_name: yzstrapiDB
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGPORT: ${DATABASE_PORT}
      PORT: ${DATABASE_PORT}
    volumes:
      - ./backend/data:/var/lib/postgresql/data/

    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'

  yzstrapiAdminer:
    container_name: yzstrapiAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '${STRAPI_ADMIN_PORT}:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=yzstrapiDB
    depends_on:
      - yzstrapiDB

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}