version: '3'
services:
  strapi:
    container_name: strapi
    image: blade86/strapi-v4:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      VIRTUAL_HOST: strapial.yeonv.com
      # VIRTUAL_PORT: ${PORT}
      LETSENCRYPT_HOST: strapial.yeonv.com
      LETSENCRYPT_EMAIL: yeonhtc+server@gmail.com
    volumes:
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
      - ./tsconfig.json:/opt/app/tsconfig.json
    ports:
      - '${STRAPI_PORT}:${STRAPI_PORT}'
    # networks:
    #   - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGPORT: ${DATABASE_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data/

    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    # networks:
    #   - strapi

  strapiAdminer:
    container_name: strapiAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '${STRAPI_ADMIN_PORT}:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=strapiDB
    # networks:
    #   - dent
    depends_on:
      - strapiDB

networks:
  default:
    external: true
    name: webproxy
